# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=128, unique=True)),
        ),
    ]
