# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b80ef69a-ab22-11e7-908c-086d41bb634c'), unique=True),
        ),
    ]
